version: "3.8"

services:
  jumble:
    container_name: jumble-nginx
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_PROXY_SERVER: ${JUMBLE_PROXY_SERVER_URL:-http://localhost:8090} 
    ports:
      - "8089:80"
    restart: unless-stopped
    networks:
        - jumble

  proxy-server:
    image: ghcr.io/danvergara/jumble-proxy-server:latest
    environment:
      - ALLOW_ORIGIN=${JUMBLE_SOCIAL_URL:-http://localhost:8089}
      - PORT=8080
    ports:
      - "8090:8080"
    networks:
        - jumble

networks:
  jumble:
